### ISSUE TITLE
General maintenance plan

### ISSUE THREAD

**Issue by lierdakil** [atom-community/markdown-preview-plus#314]
Since all current maintainers suffer from severe lack of time, this project is in dire need of help. This issue drafts a general list of maintenance tasks.

See also [milestones](https://github.com/atom-community/markdown-preview-plus/milestones) and [issues marked as "help wanted"](https://github.com/atom-community/markdown-preview-plus/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22).

In no particular order:

- [x] Going through code with a fine comb and getting rid of extraneous dependencies. For some examples, `cheerio` can be considered extraneous, since everything it's used for can be done with native DOM (see 0d57acd0e6973a7fdbfb087016d594bc3e94856d). `fs-plus` might be one too.
- [x] ~~Updating to use new features from Atom API, for instance Atom's [path watcher](https://atom.io/docs/api/v1.21.0/PathWatcher) instead of awkward and brittle dependency on atom-distributed `pathwatcher` we have now (some initial work in 892ed57)~~ This doesn't pan out, using good-old `File` API is much more straightforward and stable.
- [x] Converting code to ES6 and/or TypeScript (or Flowtyped). CoffeeScript is virtually dead, and there's little point in dragging it with us, considering its popularity is dwindling fast. On the other hand, typechecker can be a useful tool in preventing obvious-in-hindsight bugs, hence TS/Flow proposal. (#323, in progress)
- [X] Getting rid of `atom-space-pen-views`. It's deprecated, slow, and awkward. Using [atom/etch](https://github.com/atom/etch) as a framework for view layer is recommended (though it's an open question if it's even necessary here) (done as part of #323)
- [X] Sorting out the dependencies wrt `underscore-plus` and `lodash`. Could probably depend on one or the other, not both. Pretty sure `lodash` is used for it's `debounce` only. (d91f466)
- [X] Figuring out which dependencies are specific to tests and moving those to devDependencies. Pretty sure some are (d91f466)

If you want to help with something listed, but not sure where to start, feel free to create an issue for discussion, or, if such an issue already exists, join the discussion there. Please remember that if you don't get a reply straight away, it doesn't mean your desire to help isn't appreciated. It only means that sleep-deprived maintainers are preoccupied with something else.

/cc @Galadirith, @leipert -- if you'd like to add something or have comments/objections to anything listed, let me know.

**Comment by niccolomineo** [comment]
Not sure whether it's already mentioned somewhere else, but moving to Atom's collapsible pane containers,"Docks", could also be worth adding to the list.

**Comment by lierdakil** [comment]
@niccolomineo, not directly related to maintenance, so let's continue in https://github.com/atom-community/markdown-preview-plus/issues/318

**Comment by gunwald** [comment]
I don't know, whether or not this is the right place to ask this, but have you considered to join forces with the devs from [markdown-preview-enhanced](https://github.com/shd101wyy/markdown-preview-enhanced 
)?

Both approaches have a lot in common and both have their particular advantages. From a user perspective, it would be great to have one extension, with the advantages of both.

**Comment by lierdakil** [comment]
I'll be honest, I don't know anything about markdown-preview-enhanced, so can't really comment on it. It's nice knowing there's an alternative to MPP though, so even if this project eventually dies, there's at least something to switch to.

As I said initially, all current MPP maintainers suffer from severe lack of time and/or motivation. So... yeah, unless there's a lot of interest from MPE side to integrate something from MPP (which I'll be happy to facilitate), I won't really go out of my way to make it happen -- there are only 24 hours in a day, and I have to sleep sometime. I imagine it's the same for others.

Might be a good idea to let MPE devs know what features you're missing compared to MPP if you didn't do that already.
