### ISSUE TITLE
Roadmap to 3.0.0

### ISSUE THREAD

**Issue by Galadirith** [atom-community/markdown-preview-plus#89]
## 2.0.1 (2015-09-06)

Place anything that is not a bugfix/critical in `2.1.0` :D
- [x] #88: ATX headers require a space.
- [x] Update [`math.md`](https://github.com/Galadirith/markdown-preview-plus/blob/6853beef58aad7b9a7f6bc8f3397d10ef31d9513/docs/math.md) with stricter syntax.
- [x] Add [empty `env`](https://github.com/markdown-it/markdown-it/issues/110#issuecomment-108912494) argument to [`markdownIt.parse()`](https://github.com/Galadirith/markdown-preview-plus/blob/6853beef58aad7b9a7f6bc8f3397d10ef31d9513/lib/markdown-it-helper.coffee#L59) 
- [x] #92: Correct instantiation of `markdown-it`.
## 2.1.0 (2015-09-09)
- [x] #107 Fix Dom Fragment Serialization
- [x] #94 Fix installation issues/Refactoring imageWatcher. Fixes also #52
- [x] #98 Fix diff algorithm for `<ol start="1">...</ol>`
## 2.2.0 (2015-09-27)
- [x] #55 Copy equations when invoking `copyHtml()`
- [x] #56 PR to [`markdown-pdf`](https://github.com/travs/markdown-pdf) (travs/markdown-pdf#88)
- [x] #58 Add update preview diff algorithm specs
- [x] #113 Migrate to MathJax dependency [`2.4.0-electron.0.2.0`](https://github.com/Galadirith/MathJax/releases/tag/2.4.0-electron.0.2.0)
### @leipert
- [ ] #57 Pandoc PDF rendering
- [x] #85 Specs derived from [`markdown-preview`](https://github.com/atom/markdown-preview) issues
- [ ] #102 Support Pandoc `--standalone` and `--toc`
### @Galadirith

_In this release I'm mainly focusing on style issues and enhancements._
- [ ] #73 Open relative links (PR towards #72)
- [x] #139 Add option to configure `markdown-it` [`linkify`](https://github.com/Galadirith/markdown-preview-plus/blob/12432cba6c827b24eb60da3f73bbd0b28594df14/lib/markdown-it-helper.coffee#L31) option.
- [x] Merge upstream style enhancements from atom/markdown-preview#298
- [ ] #112 Ensure consistent styling across preview and `Save as HTML`
- [ ] #115 Syntax theme dropdown/customisation  
- [x] #123 Theme makes code unreadable (may be fixed by atom/markdown-preview#298)
### @Galadirith

_In this release I want to focus on enhancing our on-demand/auto source-preview sync features._
- [ ] #9 Add auto sync of source-preview for `markdown-it` backend.
- [ ] Improve on-demand sync feedback (I don't like the red box even though I added it :smile:).
- [ ] #106 Investigate sync for Pandoc backend (I do not yet know if implementing will be possible). 
### @Galadirith
- [ ] #137 Make preview active pane item when associated editor is made active pane item.

_Compiling everything through to `3.0.0` into one issue may end up bloating this issue. If that happens we can split it up but for now we'll work with just the one_.

**Comment by Galadirith** [comment]
@leipert I think we're looking good for `2.0.1`. As long as there was no other bug fixes you had locally I'll go ahead an publish :D

**Comment by leipert** [comment]
@Galadirith Go for it, I will update the Changelog once you pushed.

**Comment by Galadirith** [comment]
Fantastic :D Its now out in the wild.

**Comment by Galadirith** [comment]
@leipert thanks for merging #101. I'll wait until 2100 GMT for any late bug reports and then publish `2.0.2` :D

**Comment by leipert** [comment]
@Galadirith I somewhat wanted to speedup the release schedule of 2.1.0. I hope that is okay with you, I finally want to see these installation bugs gone.

**Comment by Galadirith** [comment]
@leipert Yep no problem those changes to the milestone are all perfectly reasonable. I went to bed think dream of ways to fix the ordered list issue #98 and I still was unsure about if it could be done by tomorrow. But I awoke with a rather uninteresting but simple solution, so rolling that out should hopefully be fine :D

**Comment by leipert** [comment]
@Galadirith Nice! Looking forward :+1:

**Comment by Galadirith** [comment]
Fantastic, well everything's in master now and passing (shame about the shield.io badges but it looks like their changing servers). I'll give it a cooling off period for the day and then publish `2.1.0` in the evening. Thanks @leipert :D

**Comment by leipert** [comment]
@Galadirith Seems like the badges are working. Everything's a go then! I will try to publish it now, because I think I should able to publish as I am a contributor to the package.

**Comment by leipert** [comment]
@Galadirith It's in the wild!

**Comment by Galadirith** [comment]
@leipert Great :D :tada: :balloon: And its really good to know you were able to publish as a contributor, I was never sure about the division of permission between Github and Atom's package repository :D Great

**Comment by Galadirith** [comment]
@leipert I hope its ok, I did rebuild the aborted `[ci skip]` b578af3d commit on wercker simply because it was the commit reflected in the badge for anyone now grabing `2.1.0` and `passing` looks better than `aborted` :D

**Comment by leipert** [comment]
Yeah. We need a thing in the future that changes the `README` before publish to show the build status for a fixed tag or commit, so that it reflects the status of the package and not of the master branch.

But that is something reaaaaaaaaaaally unimportant :dancer:

**Comment by Galadirith** [comment]
> But that is something reaaaaaaaaaaally unimportant :dancer:

Definitely :D 

I've updated `2.2.0` with a milestone target set for a couple of weeks from now :D

**Comment by Galadirith** [comment]
@leipert I'm really sorry I've been missing for the last 2 weeks, the first month of my PhD has been busy. I really hope your Thesis completion went we'll. 

I've fleshed out the next few releases with dates and issues to attack. I might still need to add some more or move things around, but thats always the case. Please do update with any issues you want to handle, and hopefully we can get back to some consistent releases. Thanks @leipert :smile:

**Comment by Galadirith** [comment]
Sorry everyone I have to bump the candidate release dates by a week.

**Comment by Galadirith** [comment]
I really apologise again to everyone waiting for the next release of MPP. I have had to move development back again due to PhD commitments.

**Comment by leipert** [comment]
@lierdakil Do you think this roadmap is still relevant?

**Comment by lierdakil** [comment]
Honestly, I have no idea. There's so much legacy here I was honestly tempted to just close all issues and start from a blank slate... it takes a while to figure out if a particular bug was fixed at some point or not. Feel free to close since there's not much active development happening anyways.

**Comment by leipert** [comment]
As already mentioned in #269, I will gladly help to start organizing issues.

**Comment by lierdakil** [comment]
Using milestones for this now.
